apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-testpolicy
  namespace: default
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories:
    policy.mcm.ibm.com/controls:
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: TestPolicy
        metadata:
          name: example-testpolicy
        spec:
          severity: low
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform
          maxClusterRoleBindingGroups: 10
          maxClusterRoleBindingUsers: 10
          maxRoleBindingGroupsPerNamespace: 2
          maxRoleBindingUsersPerNamespace: 2
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-testpolicy
  namespace: default
placementRef:
  name: placement-policy-testpolicy
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-testpolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-testpolicy
  namespace: default
spec:
  clusterLabels:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Other"]}
